import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ContactForm from "../components/contactform";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chinoismedia</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />{" "}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.main_chinois}>
          <div className={`${styles.logo} ${styles.logo_mobile}`}>
            <Image
              src="/logo_black.svg"
              alt="Logo Chinoismedia"
              width={75}
              height={75}
            />
          </div>
          <h1 className={styles.title}>
            Hi, welcome to Chinoismedia
            <span className={styles.title_green}>.</span>
          </h1>
          <p className={styles.paragraph}>
            I will be launching my website very soon. In the meantime be free to
            contact me for more information.
          </p>
          <div className={styles.scroll_down}></div>
        </div>
        <div className={styles.main_contact}>
          <div className={`${styles.logo} ${styles.logo_desktop}`}>
            <Image
              src="/logo.svg"
              alt="Logo Chinoismedia"
              width={75}
              height={75}
            />
          </div>

          <div className={styles.contact_content}>
            <div className={styles.contact_header}>
              <h2 className={styles.subtitle}>Contact us</h2>
              {/* <div className={styles.company}>
                <p className={`${styles.paragraph} ${styles.paragraph_white}`}>
                  Are you a company?
                </p>
                <input
                  className={styles.toggle_input}
                  type="checkbox"
                  id="switch"
                />
                <label className={styles.toggle_label} htmlFor="switch"></label>
              </div> */}
            </div>

            <ContactForm />
          </div>
          <div className={styles.footer}>
            <div className={styles.socials}>
              <a
                href="https://www.instagram.com/chinoismedia/"
                className={styles.socials_icon}
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/instagram.svg"
                  alt="Logo Instagram"
                  width={20}
                  height={20}
                />
              </a>
              <a
                className={styles.socials_icon}
                href="https://www.linkedin.com/in/quinten-lemmens-79666914a/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  src="/linkedn.svg"
                  alt="Logo Linkedn"
                  width={20}
                  height={20}
                />
              </a>
            </div>
            <Image src="/corner.svg" alt="Corner" width={20} height={20} />
          </div>
        </div>
      </main>
    </div>
  );
}
