import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useForm, ValidationError } from "@formspree/react";

export default function Home() {
  const [state, handleSubmit] = useForm("xjvlvqrd");

  if (state.succeeded) {
    return <p>Thanks for your submission!</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Chinoismedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.main_chinois}>
          <h1 className={styles.title}>
            Hi, welcome to Chinoismedia
            <span className={styles.title_green}>.</span>
          </h1>
          <p className={styles.paragraph}>
            I will be launching my website very soon. In the meantime be free to
            contact me for more information.
          </p>
        </div>
        <div className={styles.main_contact}>
          <div className={styles.logo}>
            <Image
              src="/logo.svg"
              alt="Logo Chinoismedia"
              width={75}
              height={75}
            />
          </div>

          <div>
            <div className={styles.contact_header}>
              <h2 className={styles.subtitle}>Contact us</h2>
              <div className={styles.company}>
                <p className={`${styles.paragraph} ${styles.paragraph_white}`}>
                  Are you a company?
                </p>
                <input
                  className={styles.toggle_input}
                  type="checkbox"
                  id="switch"
                />
                <label className={styles.toggle_label} htmlFor="switch"></label>
              </div>
            </div>

            <form className={styles.form} onSubmit={handleSubmit}>
              <div className={styles.input}>
                <label htmlFor="name" className={styles.input_label}>
                  Your name
                </label>
                <input
                  required
                  className={styles.input_field}
                  placeholder="Your name"
                  name="name"
                  type="text"
                  id="name"
                ></input>
                <ValidationError
                  className={styles.input_error}
                  prefix="Name"
                  field="name"
                  errors={state.errors}
                />
              </div>
              <div className={styles.input}>
                <label htmlFor="mail" className={styles.input_label}>
                  Your E-mail
                </label>
                <input
                  required
                  className={styles.input_field}
                  placeholder="Your E-mail"
                  name="mail"
                  type="email"
                  id="mail"
                ></input>
                <ValidationError
                  prefix="Email"
                  field="mail"
                  errors={state.errors}
                />
              </div>
              <div className={styles.input}>
                <label htmlFor="project" className={styles.input_label}>
                  What's your project about?
                </label>
                <input
                  required
                  className={styles.input_field}
                  placeholder="What's your project about?"
                  name="project"
                  type="text"
                  id="project"
                ></input>
                <ValidationError
                  className={styles.input_error}
                  prefix="Project"
                  field="project"
                  errors={state.errors}
                />
              </div>
              <div className={styles.input}>
                <label htmlFor="message" className={styles.input_label}>
                  Project description
                </label>
                <textarea
                  required
                  rows="5"
                  className={styles.input_field}
                  placeholder="Tell something more about your project.."
                  name="message"
                  id="message"
                ></textarea>
                <ValidationError
                  className={styles.input_error}
                  prefix="Message"
                  field="message"
                  errors={state.errors}
                />
              </div>

              <button
                className={styles.form_button}
                type="submit"
                disabled={state.submitting}
              >
                Send project
              </button>
              <ValidationError
                className={styles.input_error}
                errors={state.errors}
              />
            </form>
            <div className={styles.footer}>
              <div className={styles.socials}>
                <div className={styles.socials_icon}>
                  <Image
                    src="/instagram.svg"
                    alt="Logo Instagram"
                    width={20}
                    height={20}
                  />
                </div>
                <div className={styles.socials_icon}>
                  <Image
                    src="/linkedn.svg"
                    alt="Logo Linkedn"
                    width={20}
                    height={20}
                  />
                </div>
              </div>
              <Image src="/corner.svg" alt="Corner" width={20} height={20} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
